### ISSUE TITLE
Installing applications from Marketplace is broken

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-monitor#134]
```
cozy-monitor install data-system
info - Install started for data-system...
TypeError: Cannot read property 'url' of null
  at msgRepoGit (/usr/lib/node_modules/cozy-monitor/lib/stack_application.js:31:86)
  at /usr/lib/node_modules/cozy-monitor/lib/stack_application.js:72:29
  at parseBody (/usr/lib/node_modules/cozy-monitor/node_modules/cozy-clients/node_modules/request-json/main.js:35:12)
  at Request._callback (/usr/lib/node_modules/cozy-monitor/node_modules/cozy-clients/node_modules/request-json/main.js:96:18)
  at Request.self.callback (/usr/lib/node_modules/cozy-monitor/node_modules/cozy-clients/node_modules/request-json/node_modules/request/request.js:121:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/usr/lib/node_modules/cozy-monitor/node_modules/cozy-clients/node_modules/request-json/node_modules/request/request.js:978:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/usr/lib/node_modules/cozy-monitor/node_modules/cozy-clients/node_modules/request-json/node_modules/request/request.js:929:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:442:13)
```

**Comment by poupotte** [comment]
This issue is now fixed.
