### ISSUE TITLE
View compaction: TypeError: Request path contains unescaped characters.

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-monitor#140]
When trying to compact all view, a user get the following error message:
```
> cozy-monitor compact-all-views
info - Start views compaction on cozy...
_http_client.js:50
    throw new TypeError('Request path contains unescaped characters.');
    ^

TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:50:11)
    at Object.exports.request (http.js:31:10)
    at playRequest (/usr/local/lib/node_modules/cozy-monitor/node_modules/request-json-light/main.js:101:29)
    at Object.module.exports.post (/usr/local/lib/node_modules/cozy-monitor/node_modules/request-json-light/main.js:138:12)
    at JsonClient.post (/usr/local/lib/node_modules/cozy-monitor/node_modules/request-json-light/main.js:213:27)
    at module.exports.compactViews (/usr/local/lib/node_modules/cozy-monitor/lib/database.js:145:22)
    at /usr/local/lib/node_modules/cozy-monitor/lib/database.js:167:16
    at /usr/local/lib/node_modules/cozy-monitor/node_modules/async/lib/async.js:181:20
    at iterate (/usr/local/lib/node_modules/cozy-monitor/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/cozy-monitor/node_modules/async/lib/async.js:274:29
```

**Comment by clochix** [comment]
Same message when calling `views-list` :-S

**Comment by clochix** [comment]
For the record, using `cozy-monitor curlcouch '_all_docs?startkey=\"_design/\"\&endkey=\"_design0\"\&include_docs=true'` seems to work.

**Comment by clochix** [comment]
The error occurs on https://github.com/cozy/cozy-monitor/blob/master/src/database.coffee#L123
Thanks to @nicofrand, we have a sample of a path value that make the application crash: `cozy/_compact/filter-Xxxxx 4-config` (`Xxxxx 4` is the name of his phone).

We should probably open an issue on `request-json-light` to escape URLs
