### ISSUE TITLE
reset-proxy command is broken

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-monitor#76]
Reported by a French user:

Tout est lancer correctement semble-t-il par contre lorsque je fais un reset-proxy, j'obtiens l'erreur suivante :

sudo cozy-monitor reset-proxy

info - Reset proxy routes
ReferenceError: statusClient is not defined
at Command. (/usr/local/lib/node_modules/cozy-monitor/lib/main.js:520:5)
at Command. (/usr/local/lib/node_modules/cozy-monitor/node_modules/commander/lib/commander.js:235:8)
at Command.EventEmitter.emit (events.js:98:17)
at Command.parseArgs (/usr/local/lib/node_modules/cozy-monitor/node_modules/commander/lib/commander.js:406:12)
at Command.parse (/usr/local/lib/node_modules/cozy-monitor/node_modules/commander/lib/commander.js:352:15)
at Object. (/usr/local/lib/node_modules/cozy-monitor/lib/main.js:535:11)
at Object. (/usr/local/lib/node_modules/cozy-monitor/lib/main.js:541:4)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/usr/local/lib/node_modules/cozy-monitor/bin/cozy-monitor:10:3)
at Object. (/usr/local/lib/node_modules/cozy-monitor/bin/cozy-monitor:12:4)
at Module._compile (module.js:456:26)

**Comment by poupotte** [comment]
reset-proxy command should be fixed.
