### ISSUE TITLE
Error: Parsing error : Unexpected token T, body=   Token is not correct

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-monitor#95]
Trying to login I get

```
{"error":"invalid json"}
```

On another browser it works ok, so I go back to Firefox and go to History and do "forget about this site" on my cozy URL to try out removing cookies that would be problem. This seems to solve it and I can enter the cozy dashboard. I then go to status to try to upgrade my stack, and when I do, it gives me the error message and I'm back to my login problem. 

So I think I can upgrade via the command line tools and this is what I get : 

```
root@059f5cab7f31:~# cozy-monitor update-all-cozy-stack              
info - Update all cozy stack ...
error - An error occured:
error - Update all cozy stack failed.
[Error: Error: Parsing error : Unexpected token T, body= 
 Token is not correct]
```
Versions : 
```
# cozy-monitor versions

Cozy Stack:
controller: 2.0.31
data-system: 2.0.7
home: 2.0.10
proxy: 2.1.1
indexer: 1.0.0
monitor: 1.2.28

Other applications: 
blog: 1.0.0
bookmarks: 0.9.6
calendar: 1.0.23
contacts: 1.1.9
emails: 0.9.10
feeds: 1.4.1
files: 1.1.9
konnectors: 0.3.2
kyou: 0.2.1
notes: 1.0.1
photos: 1.0.14
remotestorage: 0.1.1
sync: 1.0.7


```

**Comment by poupotte** [comment]
Hello @arthurlutz ,

thanks for your report. 
Can you check your controller logs (in `/var/log/supervisor/cozy-controller-stdout...`)?

**Comment by arthurlutz** [comment]
```

node.js:299
      if (!x) throw new Error(msg || 'assertion error');
                    ^
Error: assertion error
    at process.assert (node.js:299:21)
    at process.removeListener (node.js:775:9)
    at /usr/local/lib/node_modules/cozy-controller/build/server.js:85:17
    at stopApps (/usr/local/lib/node_modules/cozy-controller/build/server/lib/controller.js:83:12)
    at Object.module.exports.stopAll (/usr/local/lib/node_modules/cozy-controller/build/server/lib/controller.js:295:10)
    at process.exitProcess (/usr/local/lib/node_modules/cozy-controller/build/server.js:83:25)
    at process.g (events.js:180:16)
    at process.EventEmitter.emit (events.js:95:17)
    at process.exit (node.js:707:17)
    at /usr/local/lib/node_modules/cozy-controller/build/server.js:92:24
```

**Comment by poupotte** [comment]
Thanks, do you have some logs before this error ?

**Comment by arthurlutz** [comment]
```
[Wed, 26 Aug 2015 20:37:46 GMT] - POST /apps/update-stack - - - - ms -  -
info - npm:install:success
info - monitor: update
info - controller: update
info - Process is stopped
info - files:stop application
info - emails:stop application
info - blog:stop application
info - konnectors:stop application
info - remotestorage:stop application
info - kyou:stop application
info - notes:stop application
info - feeds:stop application
info - bookmarks:stop application
info - photos:stop application
info - calendar:stop application
info - contacts:stop application
info - sync:stop application
info - Process exit with code 0

node.js:299
      if (!x) throw new Error(msg || 'assertion error');
                    ^
Error: assertion error
    at process.assert (node.js:299:21)
    at process.removeListener (node.js:775:9)
    at /usr/local/lib/node_modules/cozy-controller/build/server.js:85:17
    at stopApps (/usr/local/lib/node_modules/cozy-controller/build/server/lib/controller.js:83:12)
    at Object.module.exports.stopAll (/usr/local/lib/node_modules/cozy-controller/build/server/lib/controller.js:295:1
0)
    at process.exitProcess (/usr/local/lib/node_modules/cozy-controller/build/server.js:83:25)
    at process.g (events.js:180:16)
    at process.EventEmitter.emit (events.js:95:17)
    at process.exit (node.js:707:17)
    at /usr/local/lib/node_modules/cozy-controller/build/server.js:92:24
```

**Comment by poupotte** [comment]
Ok and if you try `sudo supervisorctl restart cozy-controller`, your controller restart ? With which logs ?

**Comment by clochix** [comment]
Hello @arthurlutz,
Any news ? Is this still relevant ? Thanks !
